### PR TITLE
Hide cookie consent in print styles

### PR DESCRIPTION
**Pull request by roelandvs**
- I reordered the properties based on the order of our stylelint rules
- I added `@media print` styles to hide the cookie consent

To hide the cookie consent on active projects we need to add the `@media print` styles in the CSS of those projects.

### CODE REVIEW

**Review by MartijnNieuwenhuizen — COMMENTED** [review]
@roelandvs Bit hard to review with these changes, but great that you did this.

I only don't understand you point about adding the `@print` styles to every current project. If we upgrade the cookie consent in every project, the `@print` styles that you added here should ensure the Cookie Consent is hidden when printing, right?

**Comment by MartijnNieuwenhuizen** [comment]
> @MartijnNieuwenhuizen Every project has their own cookie consent stylesheet. The stylesheet in this project is just a default/example stylesheet which is copied and adjusted in every project. [styling documentation](https://github.com/grrr-amsterdam/cookie-consent?tab=readme-ov-file#styling)

@roelandvs I understand that this is the current scenario. But I would still add this functionality to this package so you don't have to do this within every project. Options are (an `style` tag in the HTML, inline styles, etc etc). That way, this becomes a feature within this package :)

**Comment by roelandvs** [comment]
@MartijnNieuwenhuizen Ah in that sense. I added the print style to the package. I also added the print styles to every repo, because I already did that.

Should I also add this to the beta branch? I see that that version is used in some projects

**Review by MartijnNieuwenhuizen — APPROVED** [review]
LGTM!

**Pull request merged**
