### PR TITLE
Fix "Child to insert before is not a child of this node"

### PR DESCRIPTION
**Pull request by Mte90**

### CODE REVIEW

**Review by harmenjanssen — CHANGES_REQUESTED** [review]
Hi! Thanks so much for your contribution! 

Right now it's failing the tests. Can you take a look at the build and make sure the tests pass? See https://travis-ci.com/github/grrr-amsterdam/cookie-consent/builds/214570489

I'm also curious to know when you get the mentioned error?

**Comment by harmenjanssen** [comment]
Ah, I see, it's because your `main` element is not a direct child of `body`. 
I understand the problem, and I think your change is a good solution. 

To make sure everything keeps working, I would like to make sure the tests pass, but after that I will welcome this change!

**Comment by Mte90** [comment]
Seems that the build didn't started.

**Comment by martijngastkemper** [comment]
Weird. I've restarted the build.

**Comment by Mte90** [comment]
Ok this time worked and everything is red.

**Comment by harmenjanssen** [comment]
You mean green, but yeah, it is. 😉 

But I'm not entirely convinced yet: I think it would be good to throw an exception when `appendEl` is not defined. That's clearly an error, and right now it's failing silently and the developer will have no idea why this isn't working. 

Throwing an exception would clearly signal what's going wrong. Do you agree?

**Comment by Mte90** [comment]
Ops yes green, too many things in parallel.

So you want a console.log?

**Comment by harmenjanssen** [comment]
A full-on exception would have my preference:

```js
throw new Error("Unable to add cookie dialog: element does not exist.");
```

**Comment by Mte90** [comment]
Added but I guess that now the tests suite will alert that there is no dialog.

**Comment by harmenjanssen** [comment]
It's a bit weird how the tests didn't throw the error you were trying to solve in this PR.  
I'll have to think about why that is, I don't understand why the test either didn't fail before, or doesn't succeed now.

**Review by harmenjanssen — COMMENTED** [review]
Alright, I researched the root of this issue, and apparently, `appendEl` doesn't need to be an element.

`document.body.insertBefore(foo, null)` is totally fine, it will insert the node at the end of the body.

So the `appendEl !== null` check is not necessary, we only need to fix your case, where `main` is not a direct child of the body.

So I would say we do something like the following: 

```js
const appendEl = document.querySelector('main') || document.body.firstElementChild;
const container = appendEl ? appendEl.parentNode : document.body;
container.insertBefore(dialog.element, appendEl);
```

What do you think? 

Then we don't need an exception, your case is fixed, and the tests remain green.

**Comment by Mte90** [comment]
done

**Review by harmenjanssen — APPROVED** [review]
LGTM, thanks for your contribution!

**Comment by harmenjanssen** [comment]
I've published under version `1.0.4`.

**Pull request merged**
